- name: Copy backend compressed file 
  become: true
  copy:
    src: /root/project/artifact.tar.gz #/home/circleci/project/artifact.tar.gz
    dest: /home/ubuntu/backend/
- name: Extract backend files
  become: true
  shell: |
    cd /home/ubuntu/backend
    tar -vxf artifact.tar.gz
    rm artifact.tar.gz
- name : Compile and start app 
  become : true 
  shell : | 
    cd /home/ubuntu/backend
    sudo npm install
    
    pm2 stop default
    pm2 start npm -- start